### ISSUE TITLE
Auto-correct moves methods away from Sorbet sigs

### ISSUE THREAD

**Issue by bmulholland** [jeromedalbert/rubocop-obsession#3]
First of all, thanks for a great gem. Stuff like this is why I love Ruby land.

If a method has a Sorbet sig above it, then the autocorrect will move the method but not the method's sig block. These obviously must be sequential, so the result is broken code that hard to correctly understand.

Most immediately, perhaps don't auto-correct if a method has a sig above it?

**Comment by jeromedalbert** [comment]
Thanks for the report! I never used Sorbet so I'm not surprised it doesn't work. 🤠 I will look into it unless someone else wants to have a go at it.

**Comment by jeromedalbert** [comment]
Fixed in https://github.com/jeromedalbert/rubocop-obsession/commit/b7b1f4b4d16968d487d249e3b53499a37d63d9e8 and released a new version. 

Methods with Sorbet signatures should autocorrect properly now.

Let me know if you find any other issues. Thanks!

**Comment by bmulholland** [comment]
Amazing work! Thank you very much.
