### ISSUE TITLE
Wrong formatting on autocorrect 

### ISSUE THREAD

**Issue by slayer** [jeromedalbert/rubocop-obsession#5]
Hey

There is a problem with autocorrect:

Before:
<img width="1269" alt="image" src="https://github.com/user-attachments/assets/8faeb228-0b49-4d4e-b08a-64be24243592">
After
<img width="1274" alt="image" src="https://github.com/user-attachments/assets/fc6a8893-4a1a-4c80-8901-c1554561bacc">

**Comment by jeromedalbert** [comment]
Thanks for the report! I will have a look into it.

**Comment by jeromedalbert** [comment]
Fixed in version 0.1.6.
